# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraphFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gfeed', models.BooleanField(default=False)),
                ('gdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('GUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hscore', models.FloatField(default=0)),
                ('hchange', models.FloatField(default=0)),
                ('hdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('HUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NContent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfeed', models.BooleanField(default=False)),
                ('pdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('PUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtraProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headimage', models.ImageField(default='default/default_headimage.jpg', upload_to='headimages')),
                ('description', models.CharField(default='', max_length=50)),
                ('testornot', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('video', models.FileField(upload_to='videos')),
                ('cover', models.ImageField(default='default/default_video.jpg', upload_to='covers')),
                ('description', models.CharField(default='空', max_length=200)),
                ('teacher', models.CharField(default='空', max_length=5)),
                ('tag', models.CharField(default='', max_length=30)),
                ('difficulty', models.FloatField(default=0)),
                ('quality', models.FloatField(default=0)),
                ('play', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('favorite', models.IntegerField(default=0)),
                ('favorite_list', models.ManyToManyField(related_name='favorite_list', to='glgl_app.UserExtraProfile')),
                ('like_list', models.ManyToManyField(to='glgl_app.UserExtraProfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partfeedback',
            name='PVideo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glgl_app.Video'),
        ),
        migrations.AddField(
            model_name='notification',
            name='NUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glgl_app.UserExtraProfile'),
        ),
        migrations.AddField(
            model_name='history',
            name='HVideo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glgl_app.Video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glgl_app.Video'),
        ),
    ]
